spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10000 # Thời gian chờ phản hồi (ms)
      discovery:
        locator:
          enabled: true
      routes:
        - id: fallback
          uri: forward:/fallback
          predicates:
            - Path=/fallback
        - id: iam
          uri: lb://IAM
          predicates:
            - Path=/api/iam/**
          filters:
            - name: CircuitBreaker
              args:
                name: iamCircuitBreaker
                fallbackUri: forward:/fallback/iam
        #            - StripPrefix=1
        #            - name: Retry
        #              args:
        #                retries: 3
        #                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
        #                methods: GET, POST
        - id: storage
          uri: lb://STORAGE
          predicates:
            - Path=/api/storage/**
          filters:
            - name: CircuitBreaker
              args:
                name: storageCircuitBreaker
                fallbackUri: forward:/fallback/storage
#            - StripPrefix=1
#            - name: Retry
#              args:
#                retries: 3
#                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
#                methods: GET,POST

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
    group: gateway-api
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: iam
        url: /api/iam/iam-swagger/v3/api-docs
      - name: storage_service
        url: /api/storage/storage-swagger/v3/api-docs

server:
  port: 8888

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      iamCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 20
        recordExceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException

      storageCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 20
  timeout:
    instances:
      default:
        timeoutDuration: 10000ms
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
        cancel-running-future: false