server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      routes:
        - id: iam-service
#          uri: lb://iam
          uri: http://192.168.94.65:8088
          predicates:
            - Path=/iam/**
        - id: storage-service
#          uri: lb://storage
          uri: http://192.168.94.65:8099
          predicates:
            - Path=/storage/**
      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka/
    discovery:
      client:
        simple:
          registration-enabled: true
  swagger-ui:
    enabled: true
springdoc:
  api-docs:
    enabled: true
    group: gateway-api
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: API Gateway Service
        url: /v3/api-docs/gateway-api
      - name: IAM Service
        url: /iam/iam-swagger/v3/api-docs
      - name: Storage Service
        url: /storage/storage-swagger/v3/api-docs

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.client.loadbalancer: DEBUG
    org.springframework.cloud.gateway: DEBUG



