server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  client:
    register-with-eureka: false #khong tu dang ky chinh no
    fetch-registry: false # khong lay danh sach dich vu tu registry khac
  server:
    wait-time-in-ms-when-sync-empty: 0